algoritmo "semnome"
// Visite nosso site: onedaycode.com
// Inscreva-se em nosso canal: www.youtube.com/onedaycode
// Acompanhe nossa Página: www.facebook.com/onedaycode/
// Autor: João Victor Santos Pinho Teixeira
// Data : 07/09/2016
// Seção de Declarações 
var
valor1:inteiro

funcao soma(x,y:inteiro):inteiro
inicio
retorne x + y
fimfuncao

inicio
// Seção de Comandos
valor1<-soma(1,4)
escreval(valor1)
fimalgoritmo
