algoritmo "semnome"

var
A:inteiro
B:real
C:logico
D:caracter

funcao retornaInteiro():inteiro
inicio
retorne 10
fimfuncao

funcao retornaReal():real
inicio
retorne 10.5
fimfuncao

funcao retornaLogico():logico
inicio
retorne verdadeiro
fimfuncao

funcao retornaCaracter():caracter
inicio
retorne "Mae"
fimfuncaO

inicio

A<-retornaInteiro
B<-retornaReal
C<-retornaLogico
D<-retornaCaracter
escreval(A)
escreval(B)
escreval(C)
escreval(D)
fimalgoritmo
