algoritmo "Aulas de VisuALG"
// Visite nosso site: gamesparati.com
// Função : Calcula o Volume da esfera baseada no Raio
// Autor : João Victor Santos Pinho Teixeira
// Data : 23/02/2015
// Comandos usados: Atribuição de Valores a Variáveis,Divisão,Multiplicação
// Seção de Declarações
var
RAIO,ESFERA:real
inicio
// Seção de Comandos 
escreval("Qual o valor do raio?")
leia(RAIO)
ESFERA<-4/3*3.14159+(RAIO*RAIO*RAIO)
escreval("O volume da esfera teria um valor de:",ESFERA)
fimalgoritmo
