algoritmo "semnome"
// Visite nosso site: onedaycode.com
// Inscreva-se em nosso canal: www.youtube.com/onedaycode
// Acompanhe nossa Página: www.facebook.com/onedaycode/
// Autor: João Victor Santos Pinho Teixeira
// Data : 06/09/2016
// Seção de Declarações 
var
A:inteiro
palavra:caractere

procedimento DESENHA
inicio
escreval("*--------------------*")
fimprocedimento

inicio
// Seção de Comandos 
DESENHA
escreval(A)
fimalgoritmo
