algoritmo "semnome"
// Visite nosso site: onedaycode.com
// Inscreva-se em nosso canal: www.youtube.com/onedaycode
// Acompanhe nossa Página: www.facebook.com/onedaycode/
// Autor: João Victor Santos Pinho Teixeira
// Data : 07/09/2016
// Seção de Declarações 
var
A:inteiro


procedimento aumentaUm
var B:inteiro
inicio
B<-3
escreval(B)
A<-A+1
escreva(A)
fimprocedimento


inicio
// Seção de Comandos 
aumentaUm
aumentaUm
aumentaUm


fimalgoritmo
