algoritmo "semnome"
// Visite nosso site: onedaycode.com
// Inscreva-se em nosso canal: www.youtube.com/onedaycode
// Acompanhe nossa Página: www.facebook.com/onedaycode/
// Autor: João Victor Santos Pinho Teixeira
// Data : 31/08/2016
// Seção de Declarações 
var
A,B,n,m,res:inteiro

procedimento soma (x,y: inteiro)
inicio
// res é variável global
res <- x + y
fimprocedimento

inicio
n <- 4
m <- -9
soma(n,m)
escreva(res)

fimalgoritmo
