algoritmo "semnome"
// Função :
// Autor :
// Data : 10/09/2016
// Seção de Declarações 
var
time:inteiro
inicio
// Seção de Comandos 
time<-200

escreval("O-----")
timer time
limpatela

escreval("-O----")
timer time
limpatela

escreval("--O---")
timer time
limpatela

escreval("---O--")
timer time
limpatela

escreval("----O-")
timer time
limpatela

escreval("-----O")
timer time
limpatela


fimalgoritmo
