algoritmo "semnome"
// Visite nosso site: onedaycode.com
// Inscreva-se em nosso canal: www.youtube.com/onedaycode
// Acompanhe nossa Página: www.facebook.com/onedaycode/
// Autor : João Victor Santos Pinho Teixeira
// Data : 06/09/2016
// Seção de Declarações 
var
valor1,valor2:inteiro
inicio
// Seção de Comandos 
valor1<-0
enquanto (valor1<10)faca
   escreval(valor1)
   valor1<-valor1+1
fimenquanto

valor2<-0
repita
   escreval(valor2)
   valor2<-valor2+1
ate(valor1 = 10)
fimalgoritmo
