algoritmo "Aulas de VisuALG"
// Visite nosso site: onedaycode.com
// Inscreva-se em nosso canal: www.youtube.com/onedaycode
// Acompanhe nossa Página: www.facebook.com/onedaycode/
// Função : Conta de 1 a 5
// Autor : João Victor Santos Pinho Teixeira
// Data : 23/02/2015
// Comandos usados: Enquanto
// Seção de Declarações
var
X: inteiro
inicio
// Seção de Comandos
X<-1
enquanto (X<=5)faca
   escreval (X)
   X<-X+1
fimenquanto

fimalgoritmo
