algoritmo "Aulas de VisuALG"
// Visite nosso site: onedaycode.com
// Inscreva-se em nosso canal: www.youtube.com/onedaycode
// Acompanhe nossa Página: www.facebook.com/onedaycode/
// Função : Exibe os ímpares de 1 a 5
// Autor : João Victor Santos Pinho Teixeira
// Data : 23/02/2015
// Comandos usados: Enquanto, MOD
// Seção de Declarações
var
X:inteiro
inicio
// Seção de Comandos
X<-1
enquanto (X<=5)faca
   se (X MOD 2=1)entao
      escreval (X)
   fimse
   X<-X+1
fimenquanto

fimalgoritmo
