algoritmo "Aulas de VisuALG"
// Visite nosso site: onedaycode.com
// Inscreva-se em nosso canal: www.youtube.com/onedaycode
// Acompanhe nossa Página: www.facebook.com/onedaycode/
// Função : Soma de 2 em 2 até 10
// Autor : João Victor Santos Pinho Teixeira
// Data : 23/02/2015
// Comandos usados: Enquanto
// Seção de Declarações
var
X:inteiro
inicio
// Seção de Comandos
X<-2
enquanto (X<=10)faca
   escreval (X)
   X<-X+2
fimenquanto
fimalgoritmo
